### ISSUE TITLE
No suitable HttpMessageConverter

### ISSUE THREAD

**Issue by stoperan** [taskadapter/trello-java-wrapper#14]
I can not execute any method due to below issue

`Caused by: org.springframework.web.client.RestClientException: Could not extract response: no suitable HttpMessageConverter found for response type [class com.julienvey.trello.domain.Board] and content type [application/json;charset=utf-8]
`

Is it known problem?

**Comment by alexeyOnGitHub** [comment]
This ticket is older than 2 years. Closing it. Feel free to reopen if you run into this issue again, using the latest library version.
