### ISSUE TITLE
Can't manage webhooks

### ISSUE THREAD

**Issue by archi3315** [taskadapter/trello-java-wrapper#44]
The Trello webhook API is listed as supported at the README file but I can't find a way to create/delete/update webhooks.

**Comment by alexeyOnGitHub** [comment]
I think you misread the README file. there are no "checkboxes" marked next to webhook rows in README file, meaning this functionality is not implemented. 
![image](https://user-images.githubusercontent.com/239741/51089284-943d9680-171f-11e9-8246-6404b385f05c.png)

I will update the inherited README file to make this more clear
