### ISSUE TITLE
Fetching all boards of the client

### ISSUE THREAD

**Issue by NeuroAssassin** [taskadapter/trello-java-wrapper#46]
Is there some way that I could fetch all of the boards that the client sees?  For example, using the URI https://api.trello.com/1/members/me/boards?key={yourkey}&token={yourToken}.  This url is from the API docs for Trello, and it has this in Python, so I know it exists.  It's fundamental to a project I'm working on.  So is there any way I can do this?

**Comment by NeuroAssassin** [comment]
@alexeyOnGitHub Is there a way to do this?  Been waiting for over a week now for an answer.

**Comment by alexeyOnGitHub** [comment]
I see there is no "yes" marker next to   "GET /1/members/[idMember or username]/boards" item in the README, I assume this is not implemented. you are welcome to explore this and submit a PR, including tests. I can review and merge it.

**Comment by NeuroAssassin** [comment]
@alexeyOnGitHub I hate to say this, but I have no idea how to make a PR on Github.  Instead, I forked it and then edited it from there.  Please check over it though, I am not exactly fluent in Java.  I probably messed a couple things up, but I think I got most of it right.  The repo link is https://github.com/NeuroAssassin/trello-java-wrapper

Method: https://github.com/NeuroAssassin/trello-java-wrapper/blob/master/src/main/java/com/julienvey/trello/impl/TrelloImpl.java#L122

Url: https://github.com/NeuroAssassin/trello-java-wrapper/blob/master/src/main/java/com/julienvey/trello/impl/TrelloUrl.java#L10

**Comment by alexeyOnGitHub** [comment]
it may work, but need integration tests to verify this change. cannot merge API changes without tests. see CardIt and other Scala-based tests

**Comment by nstdio** [comment]
I guess this issue should be closed due to [this](https://github.com/taskadapter/trello-java-wrapper/blob/70eea6d975d85b3718630b8fd06c2417036eaa0e/src/main/java/com/julienvey/trello/Trello.java#L241).

**Comment by alexeyOnGitHub** [comment]
alright, closing. @NeuroAssassin feel free to try the new API and fix it if it does not work for you.
