### ISSUE TITLE
Additional HTTP clients.

### ISSUE THREAD

**Issue by nstdio** [taskadapter/trello-java-wrapper#51]
For enhancement I would like to suggest to provide 2 additional implementations for `TrelloHttpClient`.

First implementation would backed by [OkHttp](https://github.com/square/okhttp).

Second one is [HttpURLConnection](https://docs.oracle.com/javase/8/docs/api/java/net/HttpURLConnection.html) based implementation.

Now project includes `org.springframework:spring-web:3.2.2.RELEASE` compile dependency. After `HttpURLConnection` based implementation will be provided we can change heavy `spring-web` dependency to `compileOnly` and provide `HttpURLConnection` as a default implementation.

If you don't mind I'll provide PR for mentioned changes.

**Comment by alexeyOnGitHub** [comment]
deployed the latest version  to OSS Sonatype. it will be propagated to Maven Central within a few hours.
![image](https://user-images.githubusercontent.com/239741/52184657-ceec9900-27ca-11e9-94a7-d032777313d6.png)

**Comment by alexeyOnGitHub** [comment]
side note - recent changes:

![image](https://user-images.githubusercontent.com/239741/52184667-e62b8680-27ca-11e9-9aa9-adbab4a17428.png)
