### ISSUE TITLE
java.lang.NoClassDefFoundError: org/slf4j/LoggerFactory

### ISSUE THREAD

**Issue by staniere** [taskadapter/trello-java-wrapper#52]
Hello, 
when trying to execute this code, I got this error message : 
"   java.lang.NoClassDefFoundError: org/slf4j/LoggerFactory"

what have I missed ?

Here is my test code : 

```

import com.julienvey.trello.Trello;
import com.julienvey.trello.domain.Board;
import com.julienvey.trello.domain.TList;
import com.julienvey.trello.impl.TrelloImpl;
import com.julienvey.trello.impl.http.ApacheHttpClient;
import java.util.List;

public class TrelloRestInterface {
static String trelloKey = "66666";
static String trelloAccessToken="55555";


public TrelloRestInterface(TestEnv testEnv) {

    /*
    Properties props = System.getProperties();
    props.put("http.proxyHost", "server");
    props.put("http.proxyPort", "port");
    props.put("https.proxyHost", "server");
    props.put("https.proxyPort", "portHttps");
*/
    Trello trelloApi = new TrelloImpl(trelloKey, trelloAccessToken, new ApacheHttpClient());

    String trelloBoardForAddingCardsId = "t74KdgJM";
    Board board = trelloApi.getBoard(trelloBoardForAddingCardsId);

    List<TList> lists = board.fetchLists();
    System.out.println("Trello board\n"+board.getDesc()+"\n"+board.getName());

}
```

complete Exception trace : 
>   java.lang.NoClassDefFoundError: org/slf4j/LoggerFactory
> 	
> 	at com.julienvey.trello.impl.TrelloImpl.<clinit>(TrelloImpl.java:81)
> 	at tests.base.TrelloRestInterface.<init>(TrelloRestInterface.java:27)
> 	at tests.base.TestBase.setUp(TestBase.java:231)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:498)
> 	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
> 	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
> 	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
> 	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
> 	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
> 	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
> 	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
> 	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
> 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
> 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
> 	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
> 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
> 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
> 	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
> 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
> 	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
> 	at org.junit.runners.Suite.runChild(Suite.java:128)
> 	at org.junit.runners.Suite.runChild(Suite.java:27)
> 	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
> 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
> 	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266)
> 	at java.util.concurrent.FutureTask.run(FutureTask.java)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
> 	at java.lang.Thread.run(Thread.java:748)
> Caused by: java.lang.ClassNotFoundException: org.slf4j.LoggerFactory
> 	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
> 	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
> 	... 32 more

my maven dependency : 
 

```
>    <dependency>
>             <groupId>com.taskadapter</groupId>
>             <artifactId>trello-java-wrapper</artifactId>
>             <version>0.9</version>
>         </dependency>
```

**Comment by alexeyOnGitHub** [comment]
try adding the logging dependency explicitly. e.g. https://stackoverflow.com/questions/12926899/java-lang-noclassdeffounderror-org-slf4j-loggerfactory

**Comment by staniere** [comment]
Sorry, it was my fault. 
It was due to compilating within intellijIDEA instead of launching maven command. 
With mvn command, slf4j library was automatically found within pom.xml.
