### ISSUE TITLE
Be able to configure https.proxyHost when opening httpClient

### ISSUE THREAD

**Issue by staniere** [taskadapter/trello-java-wrapper#63]
Hello, 
I does not achieve to use this API through my proxy. 

Here is one try : 
```
    HttpClientBuilder httpClientBuilder = HttpClientBuilder.create();
    HttpHost proxy = new HttpHost(testEnv.getProxyHost(), Integer.parseInt(testEnv.getProxyPort()), "http");
    httpClientBuilder.setProxy(proxy);
    org.apache.http.impl.client.CloseableHttpClient closeableClient = httpClientBuilder.build();
    
    httpClient = new com.julienvey.trello.impl.http.ApacheHttpClient(closeableClient);

    Trello trelloApi;
    trelloApi = new TrelloImpl(trelloKey, trelloAccessToken, httpClient);
```

I get error when instantiating "new com.julienvey.trello.impl.http.ApacheHttpClient(closeableClient);": 

> Error:(141, 70) java: incompatible types: org.apache.http.impl.client.CloseableHttpClient cannot be converted to org.apache.http.impl.client.DefaultHttpClient

Is there a way to use a CloseableHttpClient to declare new instance of TrelloImpl ?
Or perhaps is there a way to pass some proxy config to DefaultHttpClient ?

**Comment by staniere** [comment]
I also tried this code which compiles but does not work : 

```
    System.setProperty("http.proxyHost", testEnv.proxyHost);
    System.setProperty("http.proxyPort", testEnv.proxyPort);
    System.setProperty("http.nonProxyHosts", testEnv.getNonProxyHosts());
    System.setProperty("https.proxyHost", testEnv.proxyHost);
    System.setProperty("https.proxyPort", testEnv.proxyPort);

    httpClient = new com.julienvey.trello.impl.http.ApacheHttpClient();

    Trello trelloApi;
    trelloApi = new TrelloImpl(trelloKey, trelloAccessToken, httpClient);
```

with this code, I get this error : 
> java.net.UnknownHostException: Ceci est habituellement une erreur temporaire qui se produit durant la résolution du nom d'hôte et qui signifie que le serveur local n'a pas reçu de réponse d'un serveur faisant autorité (api.trello.com)

**Comment by nstdio** [comment]
Hello @staniere , what version of `ApacheHttpClient` you are using?

**Comment by nstdio** [comment]
@staniere after #64 merged you are would be able to do

```
CloseableHttpClient closeableClient = httpClientBuilder.build();
httpClient = new com.julienvey.trello.impl.http.ApacheHttpClient(closeableClient);
```
and not receive compilation error.

Now `com.julienvey.trello.impl.http.ApacheHttpClient` does not rely on specific implementation of `org.apache.http.client.HttpClient`.

**Comment by staniere** [comment]
ok thank you @nstdio :)
I suppose this merge will be available in 0.11 on maven repository ?
How could I know when it will be available on maven ?

**Comment by nstdio** [comment]
@staniere your welcome. Also waiting for `0.11` myself.

**Comment by alexeyOnGitHub** [comment]
uploaded v. 0.11 to OSS Sonatype repo. it will be auto-synced to Maven Central soon

**Comment by staniere** [comment]
Hello @nstdio , 
despite my update to these new maven versions, I always get the  same error : 

```
    CloseableHttpClient closeableClient2 = httpClientBuilder.build();
    httpClient = new com.julienvey.trello.impl.http.ApacheHttpClient(closeableClient2);

```
> Error:(144, 70) java: incompatible types: org.apache.http.impl.client.CloseableHttpClient cannot be converted to org.apache.http.impl.client.DefaultHttpClient


Does I have something else to modify in my code to be able to compile ?


detail of my current pom.xml : 

>        <dependency>
>             <groupId>com.taskadapter</groupId>
>             <artifactId>trello-java-wrapper</artifactId>
>             <version>0.13</version>
>             <scope>test</scope>
>         </dependency>
>         <dependency>
>             <groupId>org.apache.httpcomponents</groupId>
>             <artifactId>httpclient</artifactId>
>             <version>4.5.7</version>
>             <scope>test</scope>
>         </dependency>

**Comment by nstdio** [comment]
Hi @staniere, frankly saying I'm surprised. I've just checked it was ok. The 
`com.julienvey.trello.impl.http.ApacheHttpClient` accepts the `org.apache.http.client.HttpClient` hence accepts `CloseableHttpClient` already implementing it.

Have you tried the `mvn clean` before compiling?

**Comment by staniere** [comment]
Hello, 
compiling with mvn clean is ok . 
And I had to struggle a little bit more in order intellij compile it too. 

So it is ok for me now. 

Sorry for this false problem
And thank you for patch, I can now go trough my proxy ! :)
